version: '3.8'

services:
  web:
    build: ./web
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    build: ./database
    environment:
      MYSQL_ROOT_PASSWORD: movie123
    volumes:
      - db_data:/var/lib/mysql
      